version: '2'

run:
  timeout: 5m
  tests: true
  relative-path-mode: gomod

linters:
  default: none
  enable:
    - asasalint
    - bidichk
    - bodyclose
    - copyloopvar
    - errcheck
    - errorlint
    - exhaustive
    - gocheckcompilerdirectives
    - gochecknoinits
    - gocritic
    - godot
    - gosec
    - govet
    - ineffassign
    - intrange
    - makezero
    - misspell
    - modernize
    - musttag
    - nilerr
    - noctx
    - nosprintfhostport
    - perfsprint
    - prealloc
    - predeclared
    - reassign
    - revive
    - rowserrcheck
    - sloglint
    - staticcheck
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - usetesting
    - wastedassign
    - whitespace
  settings:
    govet:
      enable-all: true
      disable:
        - fieldalignment
    revive:
      enable-all-rules: true
      rules:
        - name: add-constant
          disabled: true
        - name: cognitive-complexity
          disabled: true
        - name: cyclomatic
          disabled: true
        - name: exported
          disabled: true
        - name: function-length
          disabled: true
        - name: line-length-limit
          disabled: true
        - name: max-public-structs
          disabled: true
        - name: package-comments
          disabled: true
  exclusions:
    generated: lax

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
