# ### go-lib-reusable-publish
# #### source: go-lib
name: ⚡ Reusable Go Publish

on:
  workflow_call:

jobs:
  publish:
    name: Verify Go proxy publication
    runs-on:
      - nscloud-ubuntu-22.04-amd64-4x8-with-cache
      - nscloud-cache-size-50gb
      - nscloud-cache-tag-atomi-nix-store-cache-linux-amd64
    steps:
      - uses: AtomiCloud/actions.setup-nix@v3
      - uses: AtomiCloud/actions.cache-go@v2
      - name: Verify tagged module
        env:
          RELEASE_TAG: ${{ github.ref_name }}
        run: nix develop .#cd -c ./scripts/ci/publish.sh "${RELEASE_TAG}"
