# ### go-base-reusable-build
# #### source: go-base
name: ⚡ Reusable Go Build

on:
  workflow_call:

jobs:
  build:
    name: Build Go
    runs-on:
      - nscloud-ubuntu-22.04-amd64-4x8-with-cache
      - nscloud-cache-size-50gb
      - nscloud-cache-tag-atomi-nix-store-cache-linux-amd64
    steps:
      - uses: AtomiCloud/actions.setup-nix@v3
      - uses: AtomiCloud/actions.cache-go@v2
      - name: Build Go
        run: nix develop .#ci -c ./scripts/ci/build.sh
